name: meal_snap
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'


dependencies:
  path: any
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  cached_network_image: ^3.3.0
  dartz: ^0.10.1
  dio: ^5.4.0
  flutter_bloc: ^8.1.3
  flutter_screenutil: ^5.9.0
  flutter_spinkit: ^5.2.0
  fluttertoast: ^8.2.4
  google_fonts: ^6.1.0
  google_nav_bar: ^5.0.6
  image_picker: ^1.0.5
  jwt_decoder: ^2.0.1
  shimmer: ^3.0.0
  flutter_localizations:
    sdk: flutter
  get_it: ^7.6.4
  gap: ^3.0.1
  intl: ^0.18.1
  equatable: ^2.0.5
  appwrite: ^11.0.1
  flutter_dotenv: ^5.1.0
  bottom_nav_bar:
    git:
      url: https://github.com/Ansh-Rathod/bottom_nav_bar
  firebase_dynamic_links: ^5.4.8
  firebase_core: ^2.24.2
  hive_flutter: ^1.1.0
  hive: ^2.2.3
  share: ^2.0.4
  flutter_widget_from_html_core: ^0.14.10+1
  expandable_widgets: ^1.0.3+1
  flutter_widget_from_html: ^0.14.10+1
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  hive_generator:
  build_runner:




flutter:

  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - .env

  fonts:
    - family: Satoshi
      fonts:
        - asset: assets/fonts/Satoshi-Medium.ttf
    - family: Telma
      fonts:
        - asset: assets/fonts/Telma-Medium.ttf
