///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class AppAssets {
  AppAssets._();

  static const String fontsClashDisplayMedium =
      'assets/fonts/ClashDisplay-Medium.ttf';
  static const String fontsSatoshiMedium = 'assets/fonts/Satoshi-Medium.ttf';
  static const String fontsTelmaMedium = 'assets/fonts/Telma-Medium.ttf';
  static const String imagesBackround = 'assets/images/backround.png';
  static const String imagesBackroundTwo = 'assets/images/backround_two.png';
  static const String imagesImagePicker = 'assets/images/image_picker.png';
  static const String imagesLock = 'assets/images/lock.png';
  static const String imagesLogo = 'assets/images/logo.png';
  static const String imagesLogoSvg = 'assets/images/logo_svg.svg';
  static const String mealSnap = '.env';
  static const String screenshots2024010101h5713 =
      'assets/screenshots/2024-01-01_01h57_13.png';
  static const String screenshots2024010101h5730 =
      'assets/screenshots/2024-01-01_01h57_30.png';
  static const String screenshots2024010101h5754 =
      'assets/screenshots/2024-01-01_01h57_54.png';
  static const String screenshots2024010101h5816 =
      'assets/screenshots/2024-01-01_01h58_16.png';
  static const String screenshots2024010101h5844 =
      'assets/screenshots/2024-01-01_01h58_44.png';
  static const String screenshots2024010101h5905 =
      'assets/screenshots/2024-01-01_01h59_05.png';
  static const String screenshots2024010101h5922 =
      'assets/screenshots/2024-01-01_01h59_22.png';
  static const String screenshots2024010101h5943 =
      'assets/screenshots/2024-01-01_01h59_43.png';
  static const String screenshots2024010101h5955 =
      'assets/screenshots/2024-01-01_01h59_55.png';
  static const String screenshots2024010102h0013 =
      'assets/screenshots/2024-01-01_02h00_13.png';
  static const String translationsAr = 'assets/translations/ar.json';
  static const String translationsEn = 'assets/translations/en.json';
}
